# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'complicationsapp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'CVCalendar', '~> 1.2.9'
  pod 'Eureka', '~> 1.6'

  # Pods for complicationsapp

  target 'complicationsappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'complicationsappUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
